### ISSUE TITLE
strange swapping for autoprefixer

### ISSUE THREAD

**Issue by cjm771** [C-Lodder/grunt-postcss#11]
Always getting the prefixes for certain files, swapped periodically in grunt post-css, triggering a unstaged file change. My settings are as follows:

```
    postcss: {
      options: {
        map: false,
        processors: [
          require('autoprefixer-core')({
            browsers: ['last 2 versions']
          })
        ]
      },
```
**Result for certain files below (prefixes are swapped order-wise, even though this file wasn't changed at all)**
![image](https://user-images.githubusercontent.com/4239492/54058645-5141f180-41ab-11e9-9297-08947b1f5705.png)

**Comment by axten** [comment]
not sure if this is related to grunt-postcss...
can you please verify this does not happen with plain postcss?

**Comment by C-Lodder** [comment]
@cjm771 `autoprefixer-core` is old and deprecated. Please use the `autoprefixer` package

**Comment by cjm771** [comment]
Ok I’ll try it out and get back to you thanks!

**Comment by cjm771** [comment]
I think that might have fixed it. I'll close this issue for now thanks.
