### ISSUE TITLE
option to ignore sourceMappingUrl and also absolute urls to dev servers.

### ISSUE THREAD

**Issue by cjm771** [C-Lodder/grunt-postcss#13]
Currently this plugin is either ripping out or replacing my sourceMappingUrl comments. I have these generated from a seperate webpack config. currently there is no way to say 'do nothing' . 

additionally it would be nice to specify absolute path urls similar to how 'sourceMapDevTool' plugin works in webpack.here you can specify a url (for us a dev only server) and a path resolution from the config to create a url. that way you can have sourcemaps that point to a dev only server. 

Example of this could be:

``` js
    postcss: {
      options: {
        map: {
          ignoreUrls: 'http://mydev.local:8000/bundledCSS/*', //ignore existing maps if match wildcard..these are done by another build process
          publicPath: 'http://mydev.local:8000/css/', //specify abs url relative to where css file is (same as sourceMapDevTool)
          file: '[file].map' //name of map file  (same as sourceMapDevTool)
        }
    }
         
```

**Comment by cjm771** [comment]
Update: I guess I can do ignore with `{dist: {src: '!path/to/ignore/'}}` but the absolute url would be amazing thanks.

**Comment by C-Lodder** [comment]
In regards to the sourceMappingUrl comments, try:
```
map: {
  annotation: false
}
```

**Comment by C-Lodder** [comment]
Absolute URL's added https://github.com/C-Lodder/grunt-postcss/pull/31
