### ISSUE TITLE
Add way to disable ok logging 

### ISSUE THREAD

**Issue by cjm771** [C-Lodder/grunt-postcss#134]
i prefer grunt logs to only output errors vs all info, would be possible to add `options.logging =  ["warn"', "error"]` to the options to have it ignore "ok" writing for this specific task? thanks!

**Comment by C-Lodder** [comment]
Hi @cjm771,
I won't be adding any features into this package. The only reason I forked it was to allow developers to keep using it with more recent PostCSS versions.
