### ISSUE TITLE
Autoprefixer warning: "Use browserlist key in package.json or .browserslistrc file."

### ISSUE THREAD

**Issue by patrickburk1988** [C-Lodder/grunt-postcss#14]
Hello! I'm getting the following warning when using the `browsers` option with Autoprefixer as in your usage example:

> Replace Autoprefixer browsers option to Browserslist config.
> Use browserslist key in package.json or .browserslistrc file.
> 
> Using browsers option cause some error. Browserslist config 
> can be used for Babel, Autoprefixer, postcss-normalize and other tools.
> 
> If you really need to use option, rename it to overrideBrowserslist.
> 
> Learn more at:
> https://github.com/browserslist/browserslist#readme
> https://twitter.com/browserslist

Is there any way of making this package use `.browserslistrc` or the `browserlist` key in `package.json` instead of having to directly pass in the `browsers` option? For what it's worth, I haven't found any issues with the compiled CSS. The warning has been just a minor irritation so far.

**Comment by C-Lodder** [comment]
Hi @patrickburk1988 

Thanks for reporting the issue. I'll get this fixed now

**Comment by C-Lodder** [comment]
Hi @patrickburk1988 

Autoprefixer 9.6.0 deprecated the use of the `browser` option. So you can add it to your `package.json`, like so:

```
"browserslist": [
  "last 1 version"
]
```

or `.browserslistrc`, like so:

```
# Browsers that we support
last 1 version
```

**Comment by patrickburk1988** [comment]
I must have had a misplaced bracket or something. The `browserlist` key didn't work the first time I tried it, but it's working now. Thanks!

**Comment by C-Lodder** [comment]
@patrickburk1988 Glad it's now working :)
