### ISSUE TITLE
How do I correctly install this and autoprefixer?

### ISSUE THREAD

**Issue by mbomb007** [C-Lodder/grunt-postcss#19]
I am trying to get this to work with autoprefixer, but I cannot find a way that works. I keep getting this error:

	Error: Cannot find module 'autoprefixer'

`npm install --global --save-dev grunt @lodder/grunt-postcss autoprefixer`

Every time, both with `autoprefixer` and with `autoprefixer-core`, it never finds the autoprefixer.

Here is my gruntfile:

```
module.exports = function(grunt) {
  // Set Autoprefixer configuration.
  grunt.initConfig({
    postcss: {
      options: {
        map: true,
        processors: [
          require('autoprefixer')({
            browsers: [
              '> 1%',
              'last 2 versions'
            ]
          }),
        ]
      },
      dist: {
        src: '**/css/*.css'
      }
    }
  });

  // Load Autoprefixer.
  grunt.loadNpmTasks('grunt-postcss');

  // Run Autoprefixer.
  grunt.registerTask('default', ['postcss']);
};
```

**Comment by C-Lodder** [comment]
`grunt-postcss` does not ship with `autoprefixer`, so you'll need to install it manually.

Try running `npm i --save-dev autoprefixer`

and then running your task again.

**Comment by mbomb007** [comment]
I was installing it. I just found out that it cannot be installed globally to work, but it must be installed locally.
