### ISSUE TITLE
Support "browserslist" key in package.json

### ISSUE THREAD

**Issue by mbomb007** [C-Lodder/grunt-postcss#21]
At the moment, only the `browsers` key can be used in package.json. This key isn't the recommended key when looking at the [browserslist documentation](https://www.npmjs.com/package/browserslist#packagejson), which says the key should be `browserslist`.

Could you support that key as well as `browsers`?

**Comment by C-Lodder** [comment]
Autoprefixer 9.6.0 deprecated the use of the `browser` option. So you can add it to your `package.json`, like so:

```
"browserslist": [
  "last 1 version"
]
```

or `.browserslistrc`, like so:

```
# Browsers that we support
last 1 version
```

**Comment by mbomb007** [comment]
Sounds good. You should probably update it at the bottom of the README.

**Comment by C-Lodder** [comment]
Will do tomorrow, thank you
