### ISSUE TITLE
postcss 8.x support

### ISSUE THREAD

**Issue by XhmikosR** [C-Lodder/grunt-postcss#27]
https://github.com/postcss/postcss/releases/tag/8.0.0

**Comment by C-Lodder** [comment]
Thanks. Will take a look when I'm back home

**Comment by XhmikosR** [comment]
@C-Lodder we probably need to move postcss to peerDependencies too BTW.

**Comment by C-Lodder** [comment]
PR in progress: https://github.com/C-Lodder/grunt-postcss/pull/31
