### ISSUE TITLE
Deprecated folder mapping

### ISSUE THREAD

**Issue by pajinev** [C-Lodder/grunt-postcss#48]
Hello, 
this mesage start to post php storm

DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at \node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".

**Comment by C-Lodder** [comment]
Hi @pajinev This was an issue was raised in the official PostCSS repo: https://github.com/postcss/postcss/issues/1455

If you're using Node.JS 15.x, try updating to v15.6.0

**Comment by pajinev** [comment]
THX a lot. Seems to be OK.
