### ISSUE TITLE
Bad problems with .browserslistrc and browserslist option in package.json

### ISSUE THREAD

**Issue by toptalo** [C-Lodder/grunt-postcss#49]
I use `grunt-postcss` to run `autoprefixer` in my projects, but recently i've noticed that settings from my `.browserslistrc` file are ignored. I have try to move settings to `package.json` file, but it has no effect. Only helps to define option `overrideBrowserslist` in `autoprefixer` settings object.

I use:
- grunt `^1.3.0`
- grunt-cli `^1.3.2`
- @lodder/grunt-postcss `^3.0.0`
- postcss `^8.2.4`
- autoprefixer `^10.2.1`
- node `12.20.2`
- npm `6.14.11`
- macOS `10.13.6`

`.browserslistrc` file is in the same directory as a `package.json` file - in a root of project.

If I run `npx autoprefixer --info` in project directory it shows correct browsers list.

**Comment by C-Lodder** [comment]
Could you try updating autoprefixer to 10.2.4

Have you also seen this https://github.com/postcss/autoprefixer/issues/1236 ?

**Comment by toptalo** [comment]
Thanks for answer!

I update `postcss` to 8.2.6 and `autoprefixer` to 10.2.4, but it didn't help.

Even when I have set only 'IE 10' in my `.browserslistrc`, it didn't adds flexbox prefixes for ie. Only `overrideBrowserslist` option helps.

Also I have try to specify `remove: false` and different versions of `flexbox` options of `autoprefixer` - it didn't help either.

**Comment by C-Lodder** [comment]
Hi @toptalo

I've just run a test locally using `IE 10` in a newly created `.browserslistrc`, and it's working perfectly fine.

Could you provide a link to your repo and branch so I can have a look at the code you're using?

**Comment by toptalo** [comment]
I found what is going wrong in my build process.
Here is my directory tree:
```
└─ project/
   ├─ static/
   │  └─ css/
   └─ markup/
      ├─ Gruntfile.js
      ├─ package.json
      └─ .browserslistrc
```

I have use `autoprefixer` to modify files "outside of the working directory", so I specify `target.cwd` to `../static/css/`.
When I move `.browserslistrc` to the real project root (`project/.browserslistrc` instead of `project/markup/.browserslistrc`) all works fine.

This is little strange, but I can live with it.
Thanks for help!
