### ISSUE TITLE
grunt.fatal

### ISSUE THREAD

**Issue by semiromid** [C-Lodder/grunt-postcss#56]
Hello @C-Lodder 

Why are you using?  `grunt.fatal(error);`

https://gruntjs.com/api/grunt.fail

Need it use:
`grunt.fail.fatal(error);`

Because of this, I can not catch the error according to the standards of the official documentation

**Comment by C-Lodder** [comment]
Hi @semiromid,

`grunt.fatal` is an alias for `grunt.fail.fatal`, meaning they are both exactly the same.

**Comment by semiromid** [comment]
@C-Lodder 
Thank you for your answer!

Still, this is not quite the same.

Since you need to do the hook differently

```
// Instead of this
grunt.util.hooker.hook(grunt.fail, 'fatal', function(e){

});

// this
grunt.util.hooker.hook(grunt, 'fatal', function(e){

});
```

I think there should be a unified approach to the implementation of this task.

**Comment by C-Lodder** [comment]
@semiromid if you open the following file:

> node_modules/@lodder/grunt-postcss/tasks/postcss.js

and replace `grunt.fatal` with `grunt.fail.fatal`, does it solve the issue?

If so, I'm happy to make that change

**Comment by semiromid** [comment]
@C-Lodder 

Yes. Thank you!

**Comment by C-Lodder** [comment]
Perfect, thanks.

I'll make the change and release an update
