### ISSUE TITLE
Doesn't read options

### ISSUE THREAD

**Issue by semiromid** [C-Lodder/grunt-postcss#58]
Hello @C-Lodder !

Doesn't read options when I pass them.

```
  postcss: {
        lint_scss: {
            options: {
                processors: [
                  require('stylelint')({formatter: 'json'})           
                ]
            },    
            src: ['src/scss/main.scss']    
        }
    },
```

Additional information

https://stylelint.io/user-guide/usage/postcss-plugin

Example use with postcss

```
const fs = require("fs");
const less = require("postcss-less");
const postcss = require("postcss");

// Code to be processed
const code = fs.readFileSync("input.less", "utf8");

postcss([
  require("stylelint")({
    /* your options */
  }),
  require("postcss-reporter")({ clearReportedMessages: true })
])
  .process(code, {
    from: "input.less",
    syntax: less
  })
  .then(() => {})
  .catch((err) => console.error(err.stack));
```

**Comment by C-Lodder** [comment]
Hi @semiromid,

Thanks for reporting.
I'll take a look at this tomorrow or Monday

Can you confirm what version of grunt-postcss you're using?

**Comment by semiromid** [comment]
@C-Lodder 

Thank you for your quick answer! 

I use:
postcss 8.2.10
grunt-postcss 3.0.1

**Comment by C-Lodder** [comment]
What options are you trying to use that aren't working and what results are you expecting?

**Comment by semiromid** [comment]
@C-Lodder 

Thank you! This problem solved.

[https://github.com/stylelint/stylelint/issues/5249](https://github.com/stylelint/stylelint/issues/5249)
