### ISSUE TITLE
source file size is not displayed properly

### ISSUE THREAD

**Issue by axten** [C-Lodder/grunt-postcss#7]
somethings wrong with the merged PR, it always reports 0B source size:
```
1 processed stylesheet created. 0 B → 2.3 kB
```

see changes: https://github.com/nDmitry/grunt-postcss/pull/118/files

this PR was not merged correctly, storing of before and after sizes are missing

**Comment by axten** [comment]
ok iI fixed the problems in #8  #9

**Comment by C-Lodder** [comment]
thanks @axten, much appreciated

**Comment by axten** [comment]
it would be great to have this in a release :)

**Comment by C-Lodder** [comment]
@axten update released

**Comment by axten** [comment]
thanks!
